feat: add integrations page
cycle/docs pull request #176
Opened 2024-03-23 01:32 UTC by lotyp

## What was changed

Added a new "Integrations" section to the Cycle ORM documentation to showcase the available external integration packages that allow the use of Cycle ORM in other PHP frameworks.

## Why?

To inform users about available integrations with popular PHP frameworks, enhancing Cycle ORM's usability across different development environments. This update aims to support developers in leveraging Cycle ORM's features more effectively within their preferred frameworks.

## Checklist

- Any docs updates needed?
  This PR serves as the update; no further documentation changes are required.

2024-03-23 01:36 UTC, lotyp commented
Probably, Spiral Framework should also be mentioned here? 😅

2024-03-26 10:20 UTC, msmakouz requested changes

2024-03-26 10:20 UTC, msmakouz commented on docs/en/manifest.json
> +      "integrations": "Integrations"
Perhaps it's worth adding this item to the menu above the 'License' item? @roxblnfk What do you think?

2024-03-26 10:20 UTC, msmakouz commented on docs/en/integrations.md
> +Cycle ORM serves as the official ORM for the Spiral framework, supported by the `spiral/cycle-bridge` package. This integration is optimized for Spiral applications, ensuring compatibility and perfor
```suggestion
Cycle ORM serves as the official ORM for the Spiral framework, supported by the `spiral/cycle-bridge` package. This integration is optimized for Spiral applications, ensuring compatibility and performance, especially with the [RoadRunner](https://roadrunner.dev) server for long-running applications.
```

2024-03-26 15:00 UTC, lotyp commented on docs/en/manifest.json
> +      "integrations": "Integrations"
Adjusted the doc structure to place "Integrations" right after "Installation". This mirrors the dev workflow, making it easier to jump from setup to exploring integrations.

2024-03-26 19:09 UTC, msmakouz approved these changes

2024-03-27 08:52 UTC, roxblnfk commented on docs/en/intro/integrations.md
> +### Yii Framework
```suggestion
## Yii 3
```

2024-03-27 08:52 UTC, roxblnfk commented on docs/en/intro/integrations.md
> +### Laravel Framework
```suggestion
## Laravel
```

2024-03-27 08:52 UTC, roxblnfk commented on docs/en/intro/integrations.md
> +### Spiral Framework
```suggestion
## Spiral
```

2024-03-27 08:52 UTC, roxblnfk commented on docs/en/intro/integrations.md
> +## Available Integrations
```suggestion
```

2024-03-27 13:34 UTC, roxblnfk commented
https://discord.com/channels/538114875570913290/630705736019869719/1222536717517455472 might be added
https://github.com/technoly/neos-eventstore-cycleadapter

2024-03-28 18:36 UTC, roxblnfk approved these changes

2024-03-28 18:36 UTC, merged